server:
  port: 8002

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/my_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: cloud-provider-payment
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    register-with-eureka: true # 表示自己注册到eureka
    # 是否冲EurekaServer抓取已有的注册信息，单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # 注册eureka地址 集群版
  instance:
    instance-id: payment8002
    prefer-ip-address: true # 显示ip地址